//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kitap_Proje.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class kayit
    {
        public int ID { get; set; }
        public Nullable<int> o_ad { get; set; }
        public Nullable<int> gorevli { get; set; }
        public Nullable<int> kitap { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<bool> durum { get; set; }
    
        public virtual kitaplar kitaplar { get; set; }
        public virtual kullanici kullanici { get; set; }
        public virtual ogrenciler ogrenciler { get; set; }
    }
}
