//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kitap_Proje.entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kitapEntities : DbContext
    {
        public kitapEntities()
            : base("name=kitapEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<kitaplar> kitaplar { get; set; }
        public virtual DbSet<kullanici> kullanici { get; set; }
        public virtual DbSet<ogrenciler> ogrenciler { get; set; }
        public virtual DbSet<siniflar> siniflar { get; set; }
        public virtual DbSet<kayit> kayit { get; set; }
    }
}
