//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kitap_Proje.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ogrenciler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ogrenciler()
        {
            this.kayit = new HashSet<kayit>();
        }
    
        public int ID { get; set; }
        public string ogrenci_adi { get; set; }
        public string ogrenci_no { get; set; }
        public Nullable<int> sinifi { get; set; }
    
        public virtual siniflar siniflar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kayit> kayit { get; set; }
    }
}
